import type { Metadata, Viewport } from "next";
import { Outfit, Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import { RefreshBanner } from "@/components/shared/RefreshBanner";
import { CommandPaletteClient } from "@/components/shared/CommandPaletteClient";
import { LearnModeProvider } from "@/components/shared/LearnMode";
import { JsonLd } from "@/components/shared/JsonLd";
import { buildPaletteItems } from "@/lib/palette";
import { organizationJsonLd, websiteJsonLd } from "@/lib/structured-data";

// Display: warm modern geometric sans for headings + UI labels.
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-display",
  display: "swap",
});

// Body: Inter, gold standard for app readability on screen.
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-body",
  display: "swap",
});

// Mono: technical labels, code, file lists.
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-mono-display",
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#06101e",
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "AI Catch Up",
    template: "%s | AI Catch Up",
  },
  description:
    "A 60-minute AI onboarding system for the solo entrepreneur or small-team lead who became the de facto AI person by default.",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "AI Catch Up",
    description:
      "A 60-minute AI onboarding system for the solo entrepreneur or small-team lead who became the de facto AI person by default.",
    type: "website",
    url: siteUrl,
    siteName: "AI Catch Up",
    // og:image is generated by app/opengraph-image.tsx (Next.js convention).
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Catch Up",
    description:
      "A 60-minute AI onboarding system for the solo entrepreneur or small-team lead who became the de facto AI person by default.",
    // twitter:image inherits og:image when not set explicitly.
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Build palette items at request time (server-side). Items are static
  // across requests so this is cheap; could memoize later if needed.
  const paletteItems = buildPaletteItems();

  return (
    <html
      lang="en"
      className={`${outfit.variable} ${inter.variable} ${spaceMono.variable}`}
    >
      <body>
        <JsonLd data={[organizationJsonLd(), websiteJsonLd()]} />
        <LearnModeProvider>
          {children}
          <RefreshBanner />
          <CommandPaletteClient items={paletteItems} />
        </LearnModeProvider>
      </body>
    </html>
  );
}
